services:
  nginx:
    image: nginx:alpine
    container_name: be.wouterds.nuc--nginx
    mem_limit: 32mb
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bewouterdsnuc.redirectscheme.scheme=https"
      - "traefik.http.routers.bewouterdsnuc-http.rule=Host(`nuc.wouterds.be`)"
      - "traefik.http.routers.bewouterdsnuc-http.entrypoints=web"
      - "traefik.http.routers.bewouterdsnuc-http.middlewares=bewouterdsnuc"
      - "traefik.http.routers.bewouterdsnuc.rule=Host(`nuc.wouterds.be`)"
      - "traefik.http.routers.bewouterdsnuc.entrypoints=websecure"
      - "traefik.http.routers.bewouterdsnuc.tls.certresolver=myhttpchallenge"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stats.js:/etc/nginx/stats.js:ro
    networks:
      - proxy

  glances:
    image: nicolargo/glances
    container_name: be.wouterds.nuc--glances
    mem_limit: 128mb
    pid: host
    command: glances -w
    volumes:
      - /:/mnt/disk1:ro
      - /data:/mnt/disk2:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
