services:
  nginx:
    image: nginx:alpine
    container_name: com.wouterds.nuc--nginx
    mem_limit: 32mb
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.comwouterdsnuc.redirectscheme.scheme=https"
      - "traefik.http.routers.comwouterdsnuc-http.rule=Host(`nuc.wouterds.com`)"
      - "traefik.http.routers.comwouterdsnuc-http.entrypoints=web"
      - "traefik.http.routers.comwouterdsnuc-http.middlewares=comwouterdsnuc"
      - "traefik.http.routers.comwouterdsnuc.rule=Host(`nuc.wouterds.com`)"
      - "traefik.http.routers.comwouterdsnuc.entrypoints=websecure"
      - "traefik.http.routers.comwouterdsnuc.tls.certresolver=myhttpchallenge"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stats.js:/etc/nginx/stats.js:ro
    networks:
      - proxy
      - nuc

  node:
    image: ghcr.io/wouterds/nuc.wouterds.com
    mem_limit: 128mb
    container_name: com.wouterds.nuc--node
    restart: unless-stopped
    env_file: .env
    networks:
      - nuc

  glances:
    image: nicolargo/glances
    container_name: com.wouterds.nuc--glances
    mem_limit: 128mb
    restart: unless-stopped
    pid: host
    command: glances -w
    volumes:
      - /:/mnt/disk1:ro
      - /data:/mnt/disk2:ro
    networks:
      - nuc

networks:
  proxy:
    external: true
  nuc:
    name: nuc
